# name of the software
name: XivRUS

project:
  version: 0.5.5
  version_ruen:
  description: Неофициальная русская локализация FINAL FANTASY XIV
  download_url: https://github.com/endervad/ffxiv_translation/releases
  download_text: Скачать

license:
  software: MIT License
  software_url: https://opensource.org/licenses/MIT

  docs: CC BY 3.0
  docs_url: https://creativecommons.org/licenses/by/3.0/

links:
  header:
    - title: GitHub
      icon: github
      brand: true
      url: https://github.com/allejo/jekyll-docs-theme
  homepage:
    - title: Наш Discord
      icon: discord
      brand: true
      url: https://discord.gg/bSrpbd9
  footer:
    - title: GitHub
      icon: github
      brand: true
      url: https://github.com/allejo/jekyll-docs-theme
    - title: Issues
      icon: bug
      url: https://github.com/allejo/jekyll-docs-theme/issues?state=open

ui:
  mode: 'auto' # 'auto', 'dark', 'light'
  brand:
    dark: "#00ceff"
    light: "#a20000"
  border_color:
    dark: "#5f5f5f"
    light: "#dee2e6"
  header:
    trianglify: true
    dark:
      color1: "#062a48"
      color2: "#304e67"
    light:
      color1: "#080331"
      color2: "#673051"
  masthead:
    color:
      dark: "#fff"
      light: "#fff"
    align:
      homepage: 'center'
      page: 'left'

social:
  github:
    user: endervad
    repo: xivrus_v2

analytics:
  google: UA-123456-1

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true
exclude:
  - Gemfile
  - Gemfile.lock
  - jekyll-docs-theme.gemspec
  - LICENSE.md
  - README.md
  - screenshot.png
