license:
  software: MIT License
  software_url: https://opensource.org/licenses/MIT

  docs: CC BY 3.0
  docs_url: https://creativecommons.org/licenses/by/3.0/

links:
  header:
    - title: GitHub
      icon: github
      brand: true
      url: https://github.com/allejo/jekyll-docs-theme
  footer:
    - title: GitHub
      icon: github
      brand: true
      url: https://github.com/allejo/jekyll-docs-theme
    - title: Issues
      icon: bug
      url: https://github.com/allejo/jekyll-docs-theme/issues?state=open

ui:
  mode: 'dark' # 'auto', 'dark', 'light'
  brand:
    dark: "#00ceff"
    light: "#a20000"
  border_color:
    dark: "#5f5f5f"
    light: "#dee2e6"
  header:
    trianglify: true
    dark:
      color1: "#062a48"
      color2: "#304e67"
    light:
      color1: "#080331"
      color2: "#673051"
  masthead:
    color:
      dark: "#fff"
      light: "#fff"
    align:
      homepage: 'center'
      page: 'left'

analytics:
  google: UA-123456-1
